apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bvrc
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0083-tenant/ci1t-830-0083-app/devfile-sample-bvrc@sha256:2d18c28d500e7105acdd99a2381faa0695d55885e49517303e60d71b46909aeb
        name: my-nodejs
        resources: {}
status: {}
